pid = /tmp/stunnel.pid
output = /tmp/stunnel.log

[rustdesk-id]
client = yes
accept = 127.0.0.1:21116
connect = rustdesk-foodshare.fly.dev:8445

[rustdesk-relay]
client = yes
accept = 127.0.0.1:21117
connect = rustdesk-foodshare.fly.dev:8446
